# The name of the Shulker world.
worldname: "shulker"
# When this setting is activated, placing any blocks other than shulkers is prevented in the specified world.
prevent-place-other-blocks: true
# When this setting is activated, placing any blocks on top of shulkers in the specified world is prevented.
prevent-block-shulker: true
# When this setting is true, it automatically gives the broken shulker to the player.
# It only does this in the specified world.
# If there is another similar plugin that performs this function, disable this setting.
# Otherwise, there may be errors or duplicates.
auto-pickup-shulkers: true
# Please enter the license key provided when purchasing the plugin.
# If you leave it blank or enter it incorrectly, the plugin will not work.
license-key: ""