name: PrivateShulkers
version: '1.2'
main: me.deaglewolf.privateshulkers.PrivateShulkers
author: DeagleWolf
description: Shulker lock plugin for BoxPvP servers.
api-version: '1.13'
commands:
  privateshulker:
    description: main command
    aliases:
      - ps
permissions:
  ps.admin:
    default: op
  ps.bypass:
    default: op